/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STermRouteImport } from './routes/s.$term'
import { Route as LangIndexLetterRouteImport } from './routes/$lang.index.$letter'
import { Route as LangEntriesEntryIdRouteImport } from './routes/$lang.entries.$entryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STermRoute = STermRouteImport.update({
  id: '/s/$term',
  path: '/s/$term',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexLetterRoute = LangIndexLetterRouteImport.update({
  id: '/$lang/index/$letter',
  path: '/$lang/index/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const LangEntriesEntryIdRoute = LangEntriesEntryIdRouteImport.update({
  id: '/$lang/entries/$entryId',
  path: '/$lang/entries/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$term': typeof STermRoute
  '/$lang/entries/$entryId': typeof LangEntriesEntryIdRoute
  '/$lang/index/$letter': typeof LangIndexLetterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$term': typeof STermRoute
  '/$lang/entries/$entryId': typeof LangEntriesEntryIdRoute
  '/$lang/index/$letter': typeof LangIndexLetterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/$term': typeof STermRoute
  '/$lang/entries/$entryId': typeof LangEntriesEntryIdRoute
  '/$lang/index/$letter': typeof LangIndexLetterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/s/$term'
    | '/$lang/entries/$entryId'
    | '/$lang/index/$letter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$term' | '/$lang/entries/$entryId' | '/$lang/index/$letter'
  id:
    | '__root__'
    | '/'
    | '/s/$term'
    | '/$lang/entries/$entryId'
    | '/$lang/index/$letter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  STermRoute: typeof STermRoute
  LangEntriesEntryIdRoute: typeof LangEntriesEntryIdRoute
  LangIndexLetterRoute: typeof LangIndexLetterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$term': {
      id: '/s/$term'
      path: '/s/$term'
      fullPath: '/s/$term'
      preLoaderRoute: typeof STermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/index/$letter': {
      id: '/$lang/index/$letter'
      path: '/$lang/index/$letter'
      fullPath: '/$lang/index/$letter'
      preLoaderRoute: typeof LangIndexLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/entries/$entryId': {
      id: '/$lang/entries/$entryId'
      path: '/$lang/entries/$entryId'
      fullPath: '/$lang/entries/$entryId'
      preLoaderRoute: typeof LangEntriesEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  STermRoute: STermRoute,
  LangEntriesEntryIdRoute: LangEntriesEntryIdRoute,
  LangIndexLetterRoute: LangIndexLetterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
