/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STermRouteImport } from './routes/s.$term'
import { Route as EntriesEntryIdRouteImport } from './routes/entries.$entryId'
import { Route as DirIndexLetterRouteImport } from './routes/$dir.index.$letter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STermRoute = STermRouteImport.update({
  id: '/s/$term',
  path: '/s/$term',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesEntryIdRoute = EntriesEntryIdRouteImport.update({
  id: '/entries/$entryId',
  path: '/entries/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const DirIndexLetterRoute = DirIndexLetterRouteImport.update({
  id: '/$dir/index/$letter',
  path: '/$dir/index/$letter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entries/$entryId': typeof EntriesEntryIdRoute
  '/s/$term': typeof STermRoute
  '/$dir/index/$letter': typeof DirIndexLetterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entries/$entryId': typeof EntriesEntryIdRoute
  '/s/$term': typeof STermRoute
  '/$dir/index/$letter': typeof DirIndexLetterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entries/$entryId': typeof EntriesEntryIdRoute
  '/s/$term': typeof STermRoute
  '/$dir/index/$letter': typeof DirIndexLetterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entries/$entryId' | '/s/$term' | '/$dir/index/$letter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entries/$entryId' | '/s/$term' | '/$dir/index/$letter'
  id:
    | '__root__'
    | '/'
    | '/entries/$entryId'
    | '/s/$term'
    | '/$dir/index/$letter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntriesEntryIdRoute: typeof EntriesEntryIdRoute
  STermRoute: typeof STermRoute
  DirIndexLetterRoute: typeof DirIndexLetterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$term': {
      id: '/s/$term'
      path: '/s/$term'
      fullPath: '/s/$term'
      preLoaderRoute: typeof STermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$entryId': {
      id: '/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId'
      preLoaderRoute: typeof EntriesEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$dir/index/$letter': {
      id: '/$dir/index/$letter'
      path: '/$dir/index/$letter'
      fullPath: '/$dir/index/$letter'
      preLoaderRoute: typeof DirIndexLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntriesEntryIdRoute: EntriesEntryIdRoute,
  STermRoute: STermRoute,
  DirIndexLetterRoute: DirIndexLetterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
